from collections import namedtuple

import abjad

from .. import utils


def final_tweaks(
    instrument_properties: list[namedtuple],
    score: abjad.Score,
    add_instrument_names: bool = True,
    add_initial_clefs: bool = True,
    add_initial_tempo: bool = True,
    add_large_time_signatures: bool = True,
    add_final_bar_line: bool = True,
    add_miscellaneous_tweaks: bool = True,
) -> None:
    r"""
    Generates the music and creates the final score.

    Args:
        instrument_properties (list[namedtuple]): A ``list`` of ``namedtuples``, each with
            properties for an instrument. Must contain keys and values for ``container``,
            ``instrument_name``, ``short_instrument_name``, and ``context`` for all staves and staff
            groups, generated by ``create_staves()``.
        score (abjad.Score): ``abjad.Score`` created by ``generate_lilypond_file_structure()``.
        add_instrument_names: if ``True``, will call ``add_instrument_names()``. Default to
            ``True``.
        add_initial_clefs: if ``True``, will call ``add_initial_clefs()``. Default to ``True``.
        add_initial_tempo: if ``True``, will call ``add_initial_tempo()``. Default to ``True``.
        add_large_time_signatures: if ``True``, will call ``add_large_time_signatures()``. Default
            to ``True``.
        add_final_bar_line: if ``True``, will call ``add_final_bar_line()``. Default to ``True``.
        add_miscellaneous_tweaks: if ``True``, will call ``add_miscellaneous_tweaks()``. Default to
            ``True``.

    Returns:
        None
    """
    print("Final Tweaks")
    print("------------")
    print()

    if add_instrument_names:
        utils.add_instrument_names(instrument_properties)
    if add_initial_clefs:
        utils.add_initial_clefs(instrument_properties)
    if add_initial_tempo:
        utils.add_initial_tempo(score)
    if add_large_time_signatures:
        utils.add_large_time_signatures(score)
    if add_final_bar_line:
        utils.add_final_bar_line(score)
    if add_miscellaneous_tweaks:
        utils.add_miscellaneous_tweaks(score)
    print()
