from collections import namedtuple

import abjad


def add_initial_clefs(instrument_properties: list[namedtuple]) -> None:
    r"""
    Adds initial clefs to all staves.

    Args:
        instrument_properties: ``list`` of ``namedtuples``, each with properties for an instrument.
            Must contain keys and values for ``container`` and ``initial_clef`` for all staves and
            staff groups, generated by ``create_staves()``. ``initial_clef`` must be a ``str`` for
            single staves, or a ``list`` of ``str`` for staff groups.

    Returns:
        None
    """
    for instrument in instrument_properties:
        if instrument.initial_clef is None:
            continue
        elif isinstance(instrument.initial_clef, list):
            for staff, clef in zip(instrument.container, instrument.initial_clef):
                abjad.attach(
                    abjad.Clef(clef),
                    abjad.select(staff).leaf(0),
                )
        else:
            abjad.attach(
                abjad.Clef(instrument.initial_clef),
                abjad.select(instrument.container).leaf(0),
            )
