from collections import namedtuple

import abjad


def add_instrument_names(instrument_properties: list[namedtuple]) -> None:
    r"""
    Adds full and short instrument names to all staves and staff groups.

    Args:
        instrument_properties: ``list`` of ``namedtuples``, each with properties for an instrument.
            Must contain keys and values for ``container``, ``instrument_name``,
            ``short_instrument_name``, and ``context`` for all staves and staff groups, generated by
            ``create_staves()``.

    Returns:
        None
    """
    for instrument in instrument_properties:
        if instrument.instrument_name is not "":
            # for better spacing, adding whitespace to end of instrument name
            instrument_name = instrument.instrument_name
            if instrument_name[-1] != " ":
                instrument_name + " "
            # creating markup
            instrument_name_markup = abjad.StartMarkup(
                context=instrument.context,
                markup=abjad.Markup(instrument_name),
            )
            # attaching markup
            abjad.attach(
                instrument_name_markup,
                abjad.select(instrument.container).leaf(0),
            )

        if instrument.short_instrument_name is not "":
            # for better spacing, adding whitespace to end of instrument name
            short_instrument_name = instrument.short_instrument_name
            if short_instrument_name[-1] != " ":
                short_instrument_name + " "
            # creating markup
            short_instrument_name_markup = abjad.MarginMarkup(
                context=instrument.context,
                markup=abjad.Markup(short_instrument_name),
            )
            # attaching markup
            abjad.attach(
                short_instrument_name_markup,
                abjad.select(instrument.container).leaf(0),
            )
